background {
  blur_passes=3
  blur_size=8
  path=$HOME/nix-green/wallpapers/catppuccin_mocha_japanese_wallpaper_8k.png
}

general {
  immediate_render=true
}

input-field {
  monitor=
  size=250, 60
  dots_center=true
  fade_on_empty=false
  font_color=rgb(202, 211, 245)
  inner_color=rgb(30, 30, 46)
  outer_color=rgb(203, 166, 247)
  outline_thickness=5
  placeholder_text=<span foreground="##cad3f5">Password...</span>
  position=0, -80
  shadow_passes=2
}

label {
  color=rgb(202, 211, 245)
  font_family=JetBrainsMono Nerd Font
  font_size=64
  halign=center
  position=0, 100
  text=cmd[update:1000] echo "$(date +'%H:%M')"
  valign=center
}

label {
  color=rgb(202, 211, 245)
  font_family=JetBrainsMono Nerd Font
  font_size=22
  halign=center
  position=0, 30
  text=cmd[update:1000] echo "$(date +'%A, %B %d')"
  valign=center
}
