#!/usr/bin/env bash
# Report which app roles this machine's distro already provides, and print a
# ready-to-paste green.apps block for linux/system-apps.nix.
#
# Detection deliberately happens here and not during evaluation: this host runs
# with pure-eval = true, where `builtins.pathExists "/usr/bin/dolphin"` silently
# returns false, and eval-cache = true would serve stale answers even with
# --impure. Declaring the result keeps the config reproducible and reviewable.
set -euo pipefail

# role:candidate commands, best first. Add rows as roles are added to modules/apps.nix.
ROLES=(
  "terminal:ghostty kitty konsole gnome-terminal alacritty foot"
  "fileManager:dolphin nautilus thunar nemo caja"
  "calculator:kcalc gnome-calculator galculator"
  "imageViewer:gwenview loupe eog swayimg imv"
  "archiver:ark file-roller xarchiver"
  "pdfViewer:okular evince zathura"
)

# nixpkgs package the repo installs for a role today, so the report can say what
# declaring the system app would stop building.
declare -A NIX_PKG=(
  [terminal]="ghostty (flake input)"
  [calculator]="gnome-calculator"
  [imageViewer]="swayimg"
)

# System prefixes only. $PATH would match ~/.nix-profile/bin and report Nix's own
# packages back as if the distro provided them.
SYS_PREFIXES=(/usr/bin /usr/local/bin)

find_system_bin() {
  local cmd=$1 prefix
  for prefix in "${SYS_PREFIXES[@]}"; do
    [ -x "$prefix/$cmd" ] && { printf '%s\n' "$prefix/$cmd"; return 0; }
  done
  return 1
}

# Owning distro package, via whichever package manager this system has.
owner_of() {
  local path=$1
  if command -v rpm >/dev/null 2>&1; then
    rpm -qf "$path" 2>/dev/null | head -1 && return 0
  elif command -v dpkg >/dev/null 2>&1; then
    dpkg -S "$path" 2>/dev/null | head -1 | cut -d: -f1 && return 0
  elif command -v pacman >/dev/null 2>&1; then
    pacman -Qoq "$path" 2>/dev/null | head -1 && return 0
  fi
  printf 'unknown\n'
}

# .desktop file, preferring the reverse-DNS name KDE/GNOME apps ship.
desktop_of() {
  local cmd=$1 dir f
  for dir in /usr/share/applications /usr/local/share/applications; do
    [ -d "$dir" ] || continue
    for f in "$dir"/*"$cmd".desktop; do
      [ -e "$f" ] && { basename "$f"; return 0; }
    done
  done
  printf '\n'
}

# Wayland app_id. hyprctl is authoritative but only for windows open right now;
# the .desktop basename is the fallback and is usually the same string.
class_of() {
  local cmd=$1 desktop=$2 found=""
  if command -v hyprctl >/dev/null 2>&1 && command -v jq >/dev/null 2>&1; then
    found=$(hyprctl clients -j 2>/dev/null \
      | jq -r --arg c "$cmd" '.[] | select(.class | ascii_downcase | contains($c)) | .class' \
      | head -1) || true
  fi
  if [ -n "$found" ]; then
    printf '%s\thyprctl\n' "$found"
  elif [ -n "$desktop" ]; then
    printf '%s\t.desktop\n' "${desktop%.desktop}"
  else
    printf '%s\tcommand\n' "$cmd"
  fi
}

printf '# %s\n' "$(. /etc/os-release 2>/dev/null && printf '%s' "${PRETTY_NAME:-unknown system}")"
printf '# Generated by scripts/detect-system-apps.sh on %s\n' "$(date +%F)"
printf 'green.apps = {\n'

report=()
for row in "${ROLES[@]}"; do
  role=${row%%:*}
  for cmd in ${row#*:}; do
    path=$(find_system_bin "$cmd") || continue
    desktop=$(desktop_of "$cmd")
    IFS=$'\t' read -r class class_src <<<"$(class_of "$cmd" "$desktop")"

    printf '  %-12s = {\n' "$role"
    printf '    command = "%s";\n' "$cmd"
    printf '    class   = "%s";  # from %s\n' "$class" "$class_src"
    [ -n "$desktop" ] && printf '    desktop = "%s";\n' "$desktop"
    [ -n "${NIX_PKG[$role]:-}" ] && printf '    package = null;  # was %s\n' "${NIX_PKG[$role]}"
    printf '  };\n'

    report+=("$role: $path [$(owner_of "$path")]")
    break   # first candidate wins
  done
done

printf '};\n\n'
printf '# Found on this system:\n'
printf '#   %s\n' "${report[@]}"
printf '#\n'
printf '# Classes marked "from .desktop" are a guess. Open each app and check with\n'
printf '#   hyprctl clients -j | jq -r ".[].class"\n'
printf '# before trusting the float window rules.\n'
