LOCALE_ARCHIVE_2_27=/nix/store/hng3v93s41pmlcvk5r0hapgs0xwyqx5n-glibc-locales-2.42-67/lib/locale/locale-archive
NIX_PATH=$HOME/.nix-defexpr/channels${NIX_PATH:+:}$NIX_PATH
TERMINFO_DIRS=/home/green/.nix-profile/share/terminfo:$TERMINFO_DIRS${TERMINFO_DIRS:+:}/etc/terminfo:/lib/terminfo:/usr/share/terminfo
XDG_DATA_DIRS=${NIX_STATE_DIR:-/nix/var/nix}/profiles/default/share:/home/green/.nix-profile/share:/usr/share/ubuntu:/usr/local/share:/usr/share:/var/lib/snapd/desktop${XDG_DATA_DIRS:+:$XDG_DATA_DIRS}
